name: docker ci

on:
  push:
  schedule:
    - cron: "0 15 * * 0"

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)

  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: scan by docker benchmark
        id: benchmark_dockerfile
        uses: sysdiglabs/benchmark-dockerfile@v1.0.0
        with:
          # CIS 4.3 Ensure that unnecessary packages are not installed in the container (Not Scored)
          disallowedPackages: "httpd, apt"
          # CIS 4.2 Ensure that containers use only trusted base images (Not Scored)
          trustedBaseImages: "httpd, alpine"
          # CIS 4.10 Ensure secrets are not stored in Dockerfiles (Not Scored)
          secretPatterns: "secret*"

      - name: output docker benchmark scan results
        run: echo '${{ steps.benchmark_dockerfile.outputs.violation_report }}' | jq '.cis_docker_benchmark_violation_report'

      - name: scan by trivy
        uses: aquasecurity/trivy-action@0.2.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: upload trivy scan results to gitHub security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"

      - name: scan image by anchore
        id: anchore
        uses: anchore/scan-action@v3
        with:
          image: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          path: "."
          acs-report-enable: true

      - name: upload anchore scan results to gitHub security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.anchore.outputs.sarif }}
